## Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to
use the NumPy package and do some tasks related to that.

1. Create a 3x3 matrix array with values ranging from 2 to 10
2. Create a NumPy array having user input values and convert the integer type to the float type of the elements of the array. For instance: Original array [1, 2, 3, 4] Array converted to a float type: [ 1., 2.,3.,4.]
3. Write a NumPy program to append values to the end of an array. For instance: Original array: [10, 20, 30] . After that, append values to the end of the array: [10 20 30 40 50 60 70 80 90]
4. Create two NumPy arrays and add the elements of both the arrays and store the result in sumArray.
- Perform the following tasks:
  * Extract the 1st row from the array
  * Extract the last element from the array


In [2]:
import numpy as np

In [5]:
##Create a 3x3 matrix array with values ranging from 2 to 10

mat = np.random.randint(low =2, high=10, size=(3,3))
print('A 3x3 matrix array with values ranging from 2 to 10: ')
print('\n',mat)

A 3x3 matrix array with values ranging from 2 to 10: 

 [[5 6 7]
 [8 7 7]
 [4 2 6]]


In [9]:
##Create a NumPy array having user input values 
#and convert the integer type to the float type of the elements of the array. 
#For instance: Original array [1, 2, 3, 4] Array converted to a float type: [ 1., 2.,3.,4.]

no_elements = int(input('Enter the desired no of elements for array: '))
arr = []

for i in range(no_elements):
    element = int(input('Enter element: '))
    arr.append(element)
    
array = np.array(arr, dtype = float)
print("User Input: ", arr)
print("Numpy Array: ", array)

Enter the desired no of elements for array: 4
Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 4
User Input:  [1, 2, 3, 4]
Numpy Array:  [1. 2. 3. 4.]


In [27]:
## Write a NumPy program to append values to the end of an array. 
#For instance: Original array: [10, 20, 30] .
#After that, append values to the end of the array: [10 20 30 40 50 60 70 80 90]

def append_last(arr1,arr2):
    """
    appends the elements of arr2 to arr1
    """
    arr1 = np.append(arr1,arr2)
    
    return arr1

arr1 = [10, 20, 30]
arr2 = [40]
arr3 = [50,60,70,80,90]
print(append_last(arr1, arr2))  


[10 20 30 40]


In [30]:
#Create two NumPy arrays and add the elements of both the arrays and store the result in sumArray.

arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])

sumArray = np.add(arr1, arr2)
print('Sum Array: ', sumArray)

Sum Array:  [ 60  80 100 120]


In [47]:
# Create a 3x3 array having values from 10-90 (interval of 10) and store that in array1

array1 = np.arange(10,100,10).reshape((3,3))
print('A 3x3 array having values from 10-90:')
print('\n', array1)

A 3x3 array having values from 10-90:

 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [53]:
##Perform the following tasks:
# a. Extract the 1st row from the array
print('First Row: ', array1[0])
# b. Extract the last element from the array
print('Last Element: ', array1[2:,2:3])

First Row:  [10 20 30]
Last Element:  [[90]]
