## Problem Statement:

You work in XYZ Company as a Python developer. The company officials want
you to build a Python program.

1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric value and returns a NumPy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return<br>
<p> [<br>
[5, 5, 5],<br>
[5, 5, 5],<br>
[5, 5, 5],<br>
]<br></p>

2. Create a method that takes n NumPy arrays of the same dimensions, sums them and returns the answer.

3. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g<br>
<p> [<br>
[1, 2, 3],<br>
[4, 5, 6],<br>
[7, 8, 9],<br>
]<br></p>

- top_left_sub_matrix(matrix, 2, 2) -> should return: <br>
<p> [<br>
[1, 2]<br>
[4, 5]<br>
]<br></p>

4. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the bottom-right N X M sub matrix, e.g:<br>
<p> [<br>
[1, 2, 3],<br>
[4, 5, 6],<br>
[7, 8, 9],<br>
]<br></p>

- sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)<br>
<p> [<br>
[5, 6]<br>
[8, 9]<br>
]<br></p>

5. Given a 1 D NumPy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:<br>
<p> [1,1,1]<br></p>

- solution(arr) --> should return :<br>
<p> {'mean' : 1.0, 'std_dev' : 0.0}





In [1]:
import numpy as np

In [3]:
#Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric value 
#and returns a NumPy array of the given dimension filled with the given value e.g.: solve((3, 3), 5)

def make_array(shape, num):
    
    """
    creates an array of given size filled with given num
    shape : tuple: (nrows, ncols)
    num: int/float
    
    return: numpy array
    """
    
    array = np.full(shape = shape, fill_value= num)
    
    return array

make_array((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
# Create a method that takes n NumPy arrays of the same dimensions, sums them and returns the answer
def make_addition(*arrays):
    
    """
    takes n numpy arrays as input
    returns sum
    """
    add = np.zeros((1,1))
    result = [add]
    
    for i, array in enumerate(arrays):
        arr = result[i]+ array
        result.append(arr)
    return result[-1]

a1 = np.ones((3,3))
a2 = np.full((3,3), 4)
a3 = np.array([[2], [3], [1]])
a4 = np.array([[3,2,1],
              [2,1,0],
              [1,0,1]])
a5 = np.array([2])

make_addition(a1, a2, a3, a4, a5)

array([[12., 11., 10.],
       [12., 11., 10.],
       [ 9.,  8.,  9.]])

In [30]:
#Given a 2 D Array of N X M Dimension, 
#write a function that accepts this array as well as two numbers N and M. 
#The method should return the top-left N X M sub matrix

def top_left_sub_matrix(matrix, nrows, ncols):
    """
    takes 2D matrix as input
    return top left subset with shape (nrows, ncols)
    """
    return matrix[: nrows, : ncols]

M = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
])

top_left_sub_matrix(M, 2,2)

array([[1, 2],
       [4, 5]])

In [39]:
#Given a 2 D Array of N X M Dimension, 
#write a function that accepts this array as well as two numbers N and M. 
#The method should return the bottom-right N X M sub matrix,

def bottom_right_sub_matrix(matrix, nrows, ncols):
    """
    takes 2D matrix as input
    return bottom right subset with shape (nrows, ncols)
    """
    return matrix[-nrows :, -ncols :]

M = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
])

bottom_right_sub_matrix(M, 3,2)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [42]:
# Given a 1 D NumPy Array. Write a function that accepts this array as parameters. 
# The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:

def mean_std(arr):
    """
    takes 1D array and returns a dictionary of mean and std_dev
    """
    solution = {'mean' : np.mean(arr),
               'std_dev' : np.std(arr)}
    
    return solution

a = [1,1,1]
mean_std(a)

{'mean': 1.0, 'std_dev': 0.0}